services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - employee-network
        volumes:
            - rabbitmq:/var/lib/rabbitmq:cached

networks:
    employee-network:
        external: true

volumes:
    rabbitmq:
